name: Run Infra Guard tool
on:
    push:
        branches: 'feat/**'
    workflow_dispatch:

jobs:
    run-infra-gaurd-tool:
        name: Update terraform variables
        uses: ./.github/workflows/build-and-run-tool.yaml
        secrets:
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            AWS_ROLE: ${{ secrets.AWS_ROLE }}








